---
title: Corti Mx
timezone: UTC
collections:
  careers:
    title: Careers
    output: true
  services:
    title: Services
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: services
  values:
    excerpt:
    description:
    image:
    carousel-image:
    video:
    layout: page
- scope:
    path: ''
    type: careers
  values:
    excerpt:
    description:
    image:
    carousel-image:
    video:
    layout: doctors_page
- scope:
    path: ''
    type: work
  values:
    client:
    excerpt:
    description:
    image:
    carousel-image:
    video:
    has-carousel-text:
    is-carousel:
    is-selected:
    has-carousel:
    images:
    - image:
      caption:
    quote:
    cite:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post

url:
description:
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-paginate-v2
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon:
company: CORTI MX
email: corti@corti.com.mx
analytics:
logo:
per_page: 12
date_format: "%b %Y"
future: true
social:
  facebook: https://www.facebook.com/CrecerOyendo/
  instagram: https://www.instagram.com/corti_creceroyendo
  youtube: http://www.youtube.com/@CORTIMARKETING
  whatsapp: https://api.whatsapp.com/send?phone=523326345842
company: Corti Mx
event-span: Torre de consultorios piso 11, 5-A
event-address: Hospital Real San José Valle Real
event-address-short: Torre de consultorios Piso 11, 5-A
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
pagination:
  collection: posts
  enabled: true
  per_page: 6
  limit: 0
  permalink: "/:num/"
  title: ":title — :num of :max"
  sort_field: date
  sort_reverse: true
autopages:
  enabled: false
